replicaCount: 3
image:
  repository: flask-app-image
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 80
ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: app.minikube.local
      paths: []