apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app-image
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}  # Expose the service on defined port
      targetPort: 8000  # Target the port your app is listening on in the container
      nodePort: 30002
  type: {{ .Values.service.type }}